services:
  web:
    #build: .
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./docs:/usr/share/nginx/html
    #command: ["nginx", "-g", "daemon off;"] #No es necesario
    restart: unless-stopped
    container_name: rpt.ovh