services:
  web:
    #build: .
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./docs:/usr/share/nginx/html
    command: ["nginx", "-g", "daemon off;"]
    container_name: rpttai